### ISSUE TITLE
 Bug Report: Issue with Parser for Config File

### ISSUE THREAD

**Issue by Memli-Sheremeti** [DoKca42/42_vscode_ft_count_line#1]
## Bug Report: Issue with Parser for Config File

**Description:**
Hey,

Really nice tool, I'm using it since the beginning of the 42 common core.

I'm currently coding a parser for a config file and I found this bug.

```c
void foo(...) {
    char c;
    if (c == '}') 
        -----Function Lines : X ----------
}

**Comment by DoKca42** [comment]
Thanks for pointing out the bug, I'll fix it.
